export type QuickEditPhase = "idle" | "tooltip" | "prompting" | "loading" | "preview";

export interface QuickEditState {
  phase: QuickEditPhase;
  /** Selection start position (anchor may be left or right) */
  from: number;
  /** Selection end position */
  to: number;
  /**
   * The text selected across `from` and `to`. By capturing it, we ensure
   * edits still make sense if the doc shifts underneath us.
   */
  selectionText: string;
  /**
   * The user's instructions for the edit
   */
  prompt: string;
  /**
   * Code being generated by the streaming response
   */
  generatedCode: string;
  /**
   * Whether the widget was opened automatically by a selection change
   */
  autoOpen?: boolean;
}

export const initialQuickEditState: QuickEditState = {
  phase: "idle",
  from: 0,
  to: 0,
  selectionText: "",
  prompt: "",
  generatedCode: "",
  autoOpen: false,
};
